version: "3"
services:
  nifi:
    container_name: nifi
    image: apache/nifi:1.19.1
    ports:
      - 8090:8090
    restart: always
    environment:
      - NIFI_WEB_HTTP_PORT=8090
      - NIFI_JVM_HEAP_MAX=512m
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD={SENHA DO ADMIN}
      - NIFI_SENSITIVE_PROPS_KEY={SENHA DE EMCRIPTAÇÃO DE DADOS SENSÍVEIS}
    volumes:
      - ./nifi/logs:/opt/nifi/nifi-current/logs
      - ./nifi/database_repository:/opt/nifi/nifi-current/database_repository
      - nifi_data:/opt/nifi/nifi-current/data
      - nifi_extensions:/opt/nifi/nifi-current/extensions
      - nifi_conf:/opt/nifi/nifi-current/conf
      - nifi_state:/opt/nifi/nifi-current/state
      - nifi_content_repository:/opt/nifi/nifi-current/content_repository
      - nifi_flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - nifi_provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - type: bind
        source: ./drivers
        target: /opt/nifi/nifi-current/drivers
    networks:
      - nifi-net

  nifi-registry:
    container_name: nifi-registry
    image: apache/nifi-registry:1.19.1
    ports:
      - 18080:18080 
    environment:
      - JVM_OPTS=-Xmx512m -Xms512m -XX:MaxPermSize=1g
    volumes:
      - ./registry/nifi_flow_storage:/opt/nifi-registry/nifi-registry-current/flow_storage
      - ./registry/providers.xml:/opt/nifi-registry/nifi-registry-current/conf/providers.xml
      - ./registry/database:/opt/nifi-registry/nifi-registry-current/database
    networks:
      - nifi-net

volumes:
  nifi_data:
    driver: local
  nifi_extensions:
    driver: local
  nifi_conf:
    driver: local
  nifi_state:
    driver: local
  nifi_content_repository:
    driver: local
  nifi_flowfile_repository:
    driver: local
  nifi_provenance_repository:
    driver: local

networks:
  nifi-net:
    external: true